### ISSUE TITLE
Question: Reliability of meteoblue Solar Forecast?

### ISSUE THREAD

**Issue by mi-hol** [grasmax/AcOnOff#2]
"Das Laden der Batterie erfolgt in Abhängigkeit von der Solarprognose, die von https://www.meteoblue.com/ zur Verfügung gestellt wird" planst Du einen Vergleich von Progosewerten mit den real erzielten Ertragswerten?

Ich habe mir das für andere Anbieter für meinen Standort angeschaut und kam zum Schluß: Prognose ist unbrauchbar

**Comment by grasmax** [comment]
Nein, das Script entscheidet an Hand von Verbrauchs- und Prognosedaten, ob und wann die Speicherbatterien ausgeglichen oder nachgeladen werden müssen. Die Prognose von meteoblue kommt jede Stunde und ist ziemlich genau.
[eval_meteoblue.csv](https://github.com/grasmax/AcOnOff/files/12463493/eval_meteoblue.csv)
Man sieht in den Delta-Spalten der Auswertung, wie die Prognosewerte von den Ist-Werten abgewichen sind.

**Comment by grasmax** [comment]
Von: mi-hol ***@***.***> 
Gesendet: Dienstag, 29. August 2023 09:55
An: grasmax/AcOnOff ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [grasmax/AcOnOff] Question: Reliability of meteoblue Solar Forecast? (Issue #2)

 

"Das Laden der Batterie erfolgt in Abhängigkeit von der Solarprognose, die von https://www.meteoblue.com/ zu"r Verfügung gestellt wird" planst Du einen Vergleich von Progosewerten mit den real erzielten Ertragswerten?

Ich habe mir das für andere Anbieter für meinen Standort angeschaut und kam zum Schluß: Prognose ist unbrauchbar

**Comment by mi-hol** [comment]
sehr durchdachte Lösung, gefällt mir!
Würde es Sinn machen die github Funktion "Diskussionen" für weitere Fragen (die ich habe) zu nutzen?
Dann müsstest Du die Funktion aktivieren :)

**Comment by mi-hol** [comment]
> Würde es Sinn machen die github Funktion "Diskussionen" für weitere Fragen (die ich habe) zu nutzen?
> Dann müsstest Du die Funktion aktivieren :)

hoffe Du hattest das oben gesehen?

Wegen API-key für MeteoBlue, bekommt man den über https://content.meteoblue.com/en/business-solutions/weather-apis/free-weather-api ?

**Comment by grasmax** [comment]
Nein, bekommt man nicht. Den API-key für die Solarprognose habe ich mit support@meteoblue.com ausgehandelt. Kostet ne Kleinigkeit.
Für Diskussionen fehlt mir im Moment die Zeit. Aber die Frageliste sehe ich mir gerne an.

**Comment by mi-hol** [comment]
updated:
ich habe mich für den kostenlosen 1 Monat API access angemeldet und wollte mir die Prognosedaten mal anschauen, bekomme aber einen script Fehler. 
Ursache ist nach meinem Verständnis der falschen API-key.
Ist das richtig?

Wenn ich mich an den meteoblue support wende, kann ich mich da auf eine Vereinbarung / CaseID beziehen?

.json Inhalt:

```
cat pvPrognose_2023-08-30-16-58.json
{
  "error": true,
  "error_message": "Access to the package API is not available for this user"
}
```

Man sollte wohl noch alle "nicht ok" Antworten im script abfangen

DB Zugriff auskommentier
```
###### CMbSolarForecast  } ##############################################################################

mf = CMbSolarForecast()                    # Konfigdatei lesen 

#mf.VerbindeMitMariaDb()                   # Verbindung zur DB herstellen, zweite Verbindung fürs Log

mf.HolePrognose()                       # Prognose abfragen und speichern
#mf.mdb.commit()
#mf.Info2Log(f'DB aktualisiert')

mf.vEndeNormal()

```

Fehler:

```
PS C:\Users\mholzer\Documents\git\AcOnOff> python .\gh_mb_pvpro.py
Programmstart
Jetzt: 2023-08-30 16:16:26.841327, Jetzt: 2023-08-30 16:00:00
Programmstart
Traceback (most recent call last):
  File "C:\Users\mholzer\Documents\git\AcOnOff\gh_mb_pvpro.py", line 189, in HolePrognose
    modelrun = data['metadata']['modelrun_utc']
               ~~~~^^^^^^^^^^^^
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mholzer\Documents\git\AcOnOff\gh_mb_pvpro.py", line 248, in <module>
    mf.HolePrognose()                       # Prognose abfragen und speichern
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\mholzer\Documents\git\AcOnOff\gh_mb_pvpro.py", line 238, in HolePrognose
    self.Error2Log(f'Fehler in HolePrognose(): {e}')
  File "C:\Users\mholzer\Documents\git\AcOnOff\gh_mb_pvpro.py", line 107, in Error2Log
    self.__Record2Log( "error", sText)
  File "C:\Users\mholzer\Documents\git\AcOnOff\gh_mb_pvpro.py", line 88, in __Record2Log
    cur = self.mdbLog.cursor()
          ^^^^^^^^^^^
AttributeError: 'CMbSolarForecast' object has no attribute 'mdbLog'

```

log:

```
2023-08-30 16:16:26 DEBUG connectionpool.py:1048: Starting new HTTPS connection (1): my.meteoblue.com:443
2023-08-30 16:16:28 DEBUG connectionpool.py:546: https://my.meteoblue.com:443 "GET /packages/pvpro-1h?apikey=******&lat=8.96&lon=48.55&format=json&tz=Europe%2FBerlin&slope=45&kwp=0.84&facing=120&tracker=0&power_efficiency=0.95 HTTP/1.1" 403 None
```

**Comment by grasmax** [comment]
Man braucht pvpro. Und der ist nicht kostenlos.

**Comment by mi-hol** [comment]
> Die Prognose von meteoblue kommt jede Stunde und ist ziemlich genau.
> [eval_meteoblue.csv](https://github.com/grasmax/AcOnOff/files/12463493/eval_meteoblue.csv)
> Man sieht in den Delta-Spalten der Auswertung, wie die Prognosewerte von den Ist-Werten abgewichen sind.

Habe jetzt die Daten weiter angeschaut.
Erster Eindruck:

- Bei DeltaP1 haben 215 von 409 Werte eine Abweichung von größer + oder -0.15 .
Muss ich noch auf Prozent umrechnen um besser zu selektieren. 

Deshalb die Frage:
Wie ist deine Definition von "ziemlich genau"?

**Comment by grasmax** [comment]
Ich kämpfe seit September 2022 in diesen Gewerken: Projektierung, Abbruch, Erdarbeiten, Rohrverlegung, Pflastern, Zimmern, Trockenbau, Elektro, Beschaffung, Einkauf und freue mich, wenn ich dann auch noch zum Forschen, Programmieren und Dokumentieren komme. 
Ins Philosophische möchte ich jetzt nicht auch noch abtriften.
Und was ich in den letzten Jahrzehnten gelernt habe und anderen als guten Rat mitgegeben möchte ist: mit einer gesunden Unschärfe lebt man wesentlich länger.

**Comment by mi-hol** [comment]
> mit einer gesunden Unschärfe lebt man wesentlich länger.

der Meinung bin ich auch, aber als Antwort suche ich einfach einen Wert (z.B. 25% Abweichung ist für PV-Prognose schon ziemlich genau). 
Ich komme halt aus einem Bereich wo Prognoseabweichungen ausserhalb von 3% schon richtig teuer werden :)

**Comment by grasmax** [comment]
Ich bin auch auf der Suche nach Antworten ;)
Darf ich fragen, aus welchem "Bereich"? BMW? VAG? Oder Verbrennersteuerung als privates Hobby?

**Comment by mi-hol** [comment]
> privates Hobby

Hier sind nur die Hobbies relevant, mehr bei einer privaten Unterhaltung

**Comment by mi-hol** [comment]
im github profil steht jetzt mein discord name für eine Unterhaltung

**Comment by grasmax** [comment]
gib mir doch mal deine Anlagenwerte (Long, Lati, kWP, Eff und Ausrichtung), dann hole ich mit meinem APIKey ein paar Werte...

**Comment by mi-hol** [comment]
Vielen Dank.

Die nächsten Tage sehen interessant aus.
![image](https://github.com/grasmax/AcOnOff/assets/22799428/fd40d968-e49e-4aa7-82ae-e2c1760220a9)


  "Moduldaten": {
    "kWPeak": "0.84",
    "Effizienz": "0.95"
  },
  "Modulausrichtung": {
    "Neigung": 45,
    "Richtung": 120,
    "Longi": "48.55",
    "Lati": "8.96"
  },

**Comment by grasmax** [comment]
[mb_pvpro_2023-09-01-08-20_mihol.txt](https://github.com/grasmax/AcOnOff/files/12494986/mb_pvpro_2023-09-01-08-20_mihol.txt)
Rest später

**Comment by grasmax** [comment]
Sorry, das Umbenennen hat nicht richtig fkt:
[mb_pvpro_2023-09-01-08-50_mihol (5).txt](https://github.com/grasmax/AcOnOff/files/12503534/mb_pvpro_2023-09-01-08-50_mihol.5.txt)
[mb_pvpro_2023-09-01-08-50_mihol (6).txt](https://github.com/grasmax/AcOnOff/files/12503535/mb_pvpro_2023-09-01-08-50_mihol.6.txt)
[mb_pvpro_2023-09-01-08-50_mihol (7).txt](https://github.com/grasmax/AcOnOff/files/12503536/mb_pvpro_2023-09-01-08-50_mihol.7.txt)
[mb_pvpro_2023-09-01-08-50_mihol (8).txt](https://github.com/grasmax/AcOnOff/files/12503537/mb_pvpro_2023-09-01-08-50_mihol.8.txt)
[mb_pvpro_2023-09-01-08-50_mihol (9).txt](https://github.com/grasmax/AcOnOff/files/12503538/mb_pvpro_2023-09-01-08-50_mihol.9.txt)
[mb_pvpro_2023-09-01-08-50_mihol (10).txt](https://github.com/grasmax/AcOnOff/files/12503539/mb_pvpro_2023-09-01-08-50_mihol.10.txt)
[mb_pvpro_2023-09-01-08-50_mihol (11).txt](https://github.com/grasmax/AcOnOff/files/12503540/mb_pvpro_2023-09-01-08-50_mihol.11.txt)
[mb_pvpro_2023-09-01-08-50_mihol (1).txt](https://github.com/grasmax/AcOnOff/files/12503541/mb_pvpro_2023-09-01-08-50_mihol.1.txt)
[mb_pvpro_2023-09-01-08-50_mihol (2).txt](https://github.com/grasmax/AcOnOff/files/12503542/mb_pvpro_2023-09-01-08-50_mihol.2.txt)
[mb_pvpro_2023-09-01-08-50_mihol.txt](https://github.com/grasmax/AcOnOff/files/12503543/mb_pvpro_2023-09-01-08-50_mihol.txt)
[mb_pvpro_2023-09-01-08-50_mihol (4).txt](https://github.com/grasmax/AcOnOff/files/12503544/mb_pvpro_2023-09-01-08-50_mihol.4.txt)

**Comment by grasmax** [comment]
Von: support@meteoblue.com <support@meteoblue.com> 
Gesendet: Freitag, 1. September 2023 15:36
Betreff: : API+ / further interested party
Dear 
Thanks for your message,
The request is not a case we usually see, but we are fine with it as long as you maintain the testing period of 2 weeks for the testing on his side. Otherwise, he could also come to us directly with a request. 
Thanks for informing us and we remain at your disposal for any further requests.
Kind regards,
meteoblue AG

**Comment by mi-hol** [comment]
Sorry mir ist leider ein gravierender Fehler unterlaufen :(

Latitude und longitude waren vertauscht. Richtig ist:

"Moduldaten": {
"kWPeak": "0.84",
"Effizienz": "0.95"
},
"Modulausrichtung": {
"Neigung": 45,
"Richtung": 120,
"Longi": "8.96",
"Lati": "48.55"
},

**Comment by mi-hol** [comment]
> The request is not a case we usually see, but we are fine with it as long as you maintain the testing period of 2 weeks for the testing on his side. Otherwise, he could also come to us directly with a request.

Anfrage hatte ich gemacht, die wurde aber am 01. September 2023 um 16:39 Uhr abgelehnt. 
Habe mit obiger Info jetzt nochmal nachgefragt.
Wie tauschen wir unsere email Adressen sicher gegen mithören aus?

**Comment by grasmax** [comment]
Habe die Koordinaten getauscht.
Und die Endung der Dateien in txt, geändert. Frage mich, warum github das Hochladen von *.json verbietet.

**Comment by grasmax** [comment]
[mb_pvpro_2023-09-04-08-50_mihol_json.zip](https://github.com/grasmax/AcOnOff/files/12510969/mb_pvpro_2023-09-04-08-50_mihol_json.zip)

**Comment by mi-hol** [comment]
> [mb_pvpro_2023-09-04-08-50_mihol_json.zip](https://github.com/grasmax/AcOnOff/files/12510969/mb_pvpro_2023-09-04-08-50_mihol_json.zip)

Komme diese Woche nicht zur Daten-Analyse, eine Datei am Ende der Woche würde reichen.

**Comment by mi-hol** [comment]
> Anfrage hatte ich gemacht, die wurde aber am 01. September 2023 um 16:39 Uhr abgelehnt.
> Habe mit obiger Info jetzt nochmal nachgefragt.

Habe jetzt einen Testzugang für 4 Wochen erhalten
