### ISSUE TITLE
In "Inbetriebnahme eines Steuerrechners ....pdf" fehlen die notwendigen python module

### ISSUE THREAD

**Issue by mi-hol** [grasmax/AcOnOff#5]
es scheinen die folgenden zu sein

python -m pip install mariadb
python -m pip install requests

**Comment by grasmax** [comment]
Stimmt. Gut beobachtet. pip install mariadb reicht aus.

**Comment by mi-hol** [comment]
> pip install mariadb reicht aus.

Aus Sicht der syntax oder module?

**Comment by grasmax** [comment]
damit diese Zeile funktioniert: import mariadb

**Comment by grasmax** [comment]
done
